language: node_js
node_js:
- node
script: npm run lint
notifications:
  slack:
    secure: aaZgqDFFLALmJH2HJb+HF8pqY/yX9wbNTdtJipbd/KG4cPeh4fJa4X7VSsf+6z6DN/dnDTszutY3R9bxeFi2MAqJkgzPEUE2mHeGbJBz53WlnvGGytIpshFsOkwQcfvdDpa+R+SMfGf4ASyZBel9mhzNKC1of5NyYCUAx6+0iRC6TiLh26dxwyiAxiCKYwWbjtYs0VzOKMhhgJKXox9ZKzBGIeg/4UzffXh6LbK7k3TxORAFTzEsEYl3N2VOR7j+rkVXh1bMQBz0/H3WtgNIbwAVFTTA8oQF2rsyphLTMNW4k9HjPPPw0RfxPCh8EjwB4asDx/FY2/hXn2APZoVThhASuh3ZW9IVp9bAeZQ1JSvCqbC07dMbyXKJJq/PVt7hEF26b5Vgbuj9U/0PCNOXYE8sUBQXigRuErAUhpl8ObOaq7c6Q5TRN4cjo9is1A6QTqxG0sE2zgHlTgZT5vshwQBXyPOZGDU6MeaO9/hS+nWf3o0yqNCrfwNcpykW7VqmqZvRtYT45THMShp/qsDQ15mrlMBoFj7jCZ/0RwzQ+rERP8sVZrWy1QEV394NP8hpcgNpLVA2bgz4Nf4W/3QV5wsOz9tTvij3vy7YMHJAsFlOvSekFadc5umQYYLOsApcIzVzHol4zqUaJLYHjfoPB2KrIy3rEPALNJYPz+x2TL0=
